{
  "seleniumLog": [],
  "checkPoints": [],
  "errorTrace": "java.lang.NullPointerException\r\n\tat com.infostretch.automation.testng.pro.QAFTestNGListener.afterInvocation(QAFTestNGListener.java:190)\r\n\tat com.infostretch.automation.testng.pro.QAFTestNGListener2.afterInvocation(QAFTestNGListener2.java:149)\r\n\tat org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithContextStrategy.callMethod(InvokedMethodListenerInvoker.java:108)\r\n\tat org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithContextStrategy.callMethod(InvokedMethodListenerInvoker.java:104)\r\n\tat org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)\r\n\tat org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:557)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:702)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:778)\r\n\tat org.testng.TestRunner.run(TestRunner.java:632)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:366)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:39)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)\r\n\tat org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n"
}