<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="nb-lees-10" tests="2" failures="0" timestamp="10 May 2017 20:20:56 GMT" time="2.708" errors="0">
  <testcase name="@BeforeClass beforeClass" time="0.0" classname="ReportingTest">
    <failure type="org.openqa.selenium.WebDriverException" message="Failed to start execution - Access denied - bad credentials
Command duration or timeout: 2.03 seconds
Build info: version: &amp;apos;2.53.0&amp;apos;, revision: &amp;apos;35ae25b1534ae328c771e0856c93e187490ca824&amp;apos;, time: &amp;apos;2016-03-15 10:43:46&amp;apos;
System info: host: &amp;apos;nb-lees-10&amp;apos;, ip: &amp;apos;192.168.1.7&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_65&amp;apos;
Driver info: org.openqa.selenium.remote.RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: Failed to start execution - Access denied - bad credentials
Command duration or timeout: 2.03 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'nb-lees-10', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at ReportingTest.beforeClass(ReportingTest.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: Failed to start execution - Access denied - bad credentials
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'nb-lees-10', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_65'
Driver info: driver.version: PerfectoMobileDriver
	at com.perfectomobile.selenium.server.MobileLocalServerConnector.getStartExecutionResult(MobileLocalServerConnector.java:102)
	at com.perfectomobile.selenium.server.MobileLocalServerConnector.startExecution(MobileLocalServerConnector.java:57)
	at com.perfectomobile.selenium.MobileDriver.startExecution(MobileDriver.java:229)
	at com.perfectomobile.selenium.MobileDriver.init(MobileDriver.java:220)
	at com.perfectomobile.selenium.MobileDriver.<init>(MobileDriver.java:112)
	at com.perfectomobile.selenium.server.PerfectoMobileDriver.initMobileDriver(PerfectoMobileDriver.java:390)
	at com.perfectomobile.selenium.server.PerfectoMobileDriver.<init>(PerfectoMobileDriver.java:103)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.MobileDefaultSession$BrowserCreator.call(MobileDefaultSession.java:240)
	at org.openqa.selenium.remote.server.MobileDefaultSession$BrowserCreator.call(MobileDefaultSession.java:226)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.MobileDefaultSession$1.run(MobileDefaultSession.java:188)
	... 3 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass beforeClass -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="ReportingTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at ReportingTest.beforeMethod(ReportingTest.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="ReportingTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at ReportingTest.beforeMethod(ReportingTest.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterClass afterClass" time="0.0" classname="ReportingTest">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="googleSearch1" time="0.003" classname="ReportingTest">
    <skipped/>
  </testcase> <!-- googleSearch1 -->
  <testcase name="googleSearch2" time="0.003" classname="ReportingTest">
    <skipped/>
  </testcase> <!-- googleSearch2 -->
</testsuite>
